### ISSUE TITLE
Graphical glitches in MechWarrior 2 Titanium Edition

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/ForceD3D9On12#1]
This is one of the game that has worked with this wrapper. But there are major graphical glitches, and instabilities. Let's start one by one, here's the mission.
![forced3d9on12mech2tit](https://user-images.githubusercontent.com/64649734/159157461-8ee94ee4-cb18-446a-99dd-6611ec38f776.png)
.

**Comment by narzoul** [comment]
As the readme says: "D3D9On12 is a completely independent project. No support will be provided for it here."
