### ISSUE TITLE
Intermittently getting Error (0x8876086A) During calls to CreateDeviceEx()

### ISSUE THREAD

**Issue by prateekchauhan1108** [narzoul/ForceD3D9On12#4]
We have a DX9 application running on an Intel Iris XE GPU (which uses D3D9on12 for Directx9 support). During calls to CreateDeviceEx() we intermittently get a 0x8876086A error code. As for our usage when we call:
 
1.	DeviceType is D3DDEVTYPE_HAL
2.	BehaviorFlags are set to “D3DCREATE_HARDWARE_VERTEXPROCESSING | D3DCREATE_NOWINDOWCHANGES | D3DCREATE_MULTITHREADED | D3DCREATE_FPU_PRESERVE”
3.	pFullscreenDisplayMode is null
 
And these are the presentation parameters used:
 
    pp.BackBufferWidth = 1;
    pp.BackBufferHeight = 1;
    pp.Windowed = TRUE;
    pp.SwapEffect = D3DSWAPEFFECT_COPY;
    pp.BackBufferFormat = D3DFMT_UNKNOWN;
    pp.hDeviceWindow = hwnd;
    pp.Flags = D3DPRESENTFLAG_VIDEO;
    pp.PresentationInterval = D3DPRESENT_INTERVAL_DEFAULT;

**Comment by narzoul** [comment]
I think you posted this in the wrong project, you probably meant to open an issue here:
https://github.com/microsoft/D3D9On12/issues
